- hosts: 
  - macos
  name: Git Playbook
  tasks:
    - git_config:
        name: "{{ item.name }}"
        scope: global
        value: "{{ item.value }}"
      with_items:
        - {name: "alias.st", value: "status"}
        - {name: "alias.br", value: "branch"}
        - {name: "alias.ci", value: "commit"}
        - {name: "alias.co", value: "checkout"}
        - {name: "user.email", value: "matt@m0smith.com"}
        - {name: "user.name", value: "Matthew O. Smith"}

  