- hosts: macos
  name: ZSH Playbook
  vars:
    zshrc_path: "~/.zshrc"
    plugins: "git mvn python vscode pipenv pass docker jsontools history web-search zsh-autosuggestions"
  tasks:
    - name: Gather facts
      setup:
    - name: Set variable if host is macOS
      set_fact:
        macos_plugin: "macos"
      when: ansible_os_family == "Darwin"
    - name: Install oh-my-zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      args:
        creates: "~/.oh-my-zsh"
    - name: Install zsh-autosuggestions
      shell: "git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions"
      args:
        creates: "{{ansible_env.HOME}}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    - name: Update .zshrc to include plugins
      ansible.builtin.lineinfile:
        path: "{{ zshrc_path }}"
        regexp: "^plugins="
        line: "plugins=({{ plugins }} {{macos_plugin | default('')}})"
    - name: Ensure pyenv block is present in .zshrc
      ansible.builtin.lineinfile:
        path: "{{ zshrc_path }}"
        insertafter: EOF
        block: |
          if command -v pyenv &> /dev/null; then
              export PATH="$HOME/.pyenv/bin:$PATH"
              eval "$(pyenv init --path)"
              eval "$(pyenv init -)"
          fi
    - name: Ensure .local/bin block is present in .zshrc
      ansible.builtin.lineinfile:
        path: "{{ zshrc_path }}"
        insertafter: EOF
        block: |
          if test -d $HOME/.local/bin; then
              export PATH="$HOME/.local/bin:$PATH"
          fi


