(when (string-equal system-type "cygwin" )
  (setq malabar-util-path-separator ";")
  (setq malabar-util-path-filter 'cygwin-convert-file-name-to-windows)
  (setq malabar-util-groovy-file-filter 'malabar-util-reverse-slash)
)
